sudo: required
services:
    -docker


before_install:
    - docker build -t krish1206/docker-react -f Dockerfile.dev .

script:
    - docker run krish1206/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-373521354105"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"